### PR TITLE
All version classes should be serializable

### PR DESCRIPTION
**Pull request by rbellamy**
Serializable version classes with unit test

---
This change is [Reviewable](https://reviewable.io/reviews/zafarkhaja/jsemver/31)

### CODE REVIEW

**Comment by rbellamy** [comment]
@zafarkhaja my PR is not the oldest on your list, so by no means am I trying to jump ahead in line - this is just a gentle ping to find out if you have any idea when you'll have a chance to merge these outstanding PR's?

**Comment by rbellamy** [comment]
@zafarkhaja - any word at all?

**Comment by rbellamy** [comment]
Gah, this is why GitHub Organizations are so useful. Once again, another project that is essentially dead because the original author couldn't be bothered...

**Comment by zafarkhaja** [comment]
Hello Richard, I hope you're doing well!

Your frustration was valid, and I'm sorry it took me this long to get back to you.

I appreciate you taking the time and effort to contribute, however I'd prefer serialization proxy pattern to using the default serialized form. I wasn't sure if you'd be still interested to resubmit, and, anyway, wanted to speed things up to clear the backlog as soon as possible, so I went ahead and implemented the feature myself (8c22fdf).

Have a nice day,

**Pull request closed without merging**
